services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack-chaos-engineering
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
      - "${LOCALSTACK_EDGE_PORT:-4510-4559}:4510-4559"
      - "5353:53/tcp"
      - "5353:53/udp"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - SERVICES=${SERVICES:-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-docker}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY:-0.0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - DNS_ADDRESS=0.0.0.0
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  localstack-net:
    driver: bridge